name: Github Actions for Sending ZenQuotes to a Slack Channel

on:
  workflow_dispatch: 
  #workflow_dispatch helps run workflow anytime with a single click.
  schedule:
    # Runs "Every Monday and Friday at 00:00 UTC" (see https://crontab.guru)
    - cron: "00 00 * * 1,5"   

jobs:
  zenbot:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Node" 
        uses: actions/setup-node@v2

      - name: "Checkout Code"  
        uses: actions/checkout@v2

      - name: "Install NPM dependencies"  
        run: npm install

      - name: "Run Code"  
        run: npm start
        env:
          SLACK_URL:  ${{secrets.SLACK_URL}}        
